export const METRICS = {
  totalUsers: {
    title: "Total Users",
    value: 1289126000,
    iconUrl: {
      dark: "/UsersThreeFill.png",
      light: "/UsersThreeFillLight.png"
    },
  },
  activeUsers: {
    title: "Active Users",
    value: 567810456,
    iconUrl: {
      dark: "/UsersThreeActiveFill.png",
      light: "/UsersThreeActiveFillLight.png"
    },
  },
  totalStreams: {
    title: "Total Streams",
    value: 129648000,
    iconUrl: {
      dark: "/MusicFill.png",
      light: "/MusicFillLight.png"
    },
  },
  revenue: {
    title: "Revenue",
    value: 14094570000,
    iconUrl: {
      dark: "/DollarGreenFill.png",
      light: "/DollarGreenFillLight.png"
    },
  },
  topArtist: {
    title: "Top Artist",
    value: "Bruno Mars",
    valueIconUrl: {
      dark: "/TrendingFill.png",
      light: "/TrendingFillLight.png"
    },
    iconUrl: {
      dark: "/UserArtist.png",
      light: "/UserArtistLight.png"
    },
  },
};

export const USER_GROWTH = [
  { totalUsers: 1_100_000_000, activeUsers: 883_000_000 },
  { totalUsers: 1_105_000_000, activeUsers: 760_000_000 },
  { totalUsers: 1_095_000_000, activeUsers: 887_000_000 },
  { totalUsers: 1_085_000_000, activeUsers: 971_000_000 },
  { totalUsers: 1_100_000_000, activeUsers: 748_000_000 },
  { totalUsers: 1_010_000_000, activeUsers: 802_000_000 },
  { totalUsers: 995_000_000, activeUsers: 816_000_000 },
  { totalUsers: 1_110_000_000, activeUsers: 653_000_000 },
  { totalUsers: 1_100_000_000, activeUsers: 989_000_000 },
  { totalUsers: 1_105_000_000, activeUsers: 891_000_000 },
  { totalUsers: 1_100_000_000, activeUsers: 769_000_000 },
  { totalUsers: 1_110_000_000, activeUsers: 973_000_000 },
];

export const REVENUE_DISTRIBUTION = {
  ads: {
    name: "Ads",
    value: 2400000000,
    color: "#0088FE",
  },
  subscriptions: {
    name: "Subscription",
    value: 7500000000,
    color: "#00C49F",
  },
  events: {
    name: "Events",
    value: 1100000000,
    color: "#FFBB28",
  },
  promotions: {
    name: "Promotions",
    value: 500000000,
    color: "#FF8042",
  },
  misc: {
    name: "Misc",
    value: 230000000,
    color: "#4B8B4B",
  },
};

export const TOP_5_STREAMS = [
  {
    name: "STAR WALKIN - Lil Nas'",
    streamCount: 2100000000,
    color: "#006699",
  },
  {
    name: "POWER G-DRAGON",
    streamCount: 1900000000,
    color: "#2A7F10",
  },
  {
    name: "Daylight - David Kushner",
    streamCount: 1700000000,
    color: "#99804D",
  },
  {
    name: "Middle Of The Night - Elle Duhe",
    streamCount: 1500000000,
    color: "#009699",
  },
  {
    name: "Top or Cliff - KIMSEJONG",
    streamCount: 1300000000,
    color: "#5A4099",
  },
];

export const RECENT_STREAMS = [
  {
    "Song Name": "Blinding Lights",
    "Artist": "The Weeknd",
    "Date Streamed": "2024-09-01",
    "Stream Count": 3_250_000,
    "User ID": 1042,
    "Revenue Source": "ads",
    "Revenue Generated": 2.5,
  },
  {
    "Song Name": "Shape of You",
    "Artist": "Ed Sheeran",
    "Date Streamed": "2024-09-01",
    "Stream Count": 4_100_000,
    "User ID": 1093,
    "Revenue Source": "subscription",
    "Revenue Generated": 3.8,
  },
  {
    "Song Name": "Uptown Funk",
    "Artist": "Mark Ronson ft. Bruno Mars",
    "Date Streamed": "2024-09-01",
    "Stream Count": 2_700_000,
    "User ID": 1068,
    "Revenue Source": "ads",
    "Revenue Generated": 2.1,
  },
  {
    "Song Name": "Someone Like You",
    "Artist": "Adele",
    "Date Streamed": "2024-09-01",
    "Stream Count": 1_900_000,
    "User ID": 1005,
    "Revenue Source": "subscription",
    "Revenue Generated": 1.6,
  },
  {
    "Song Name": "Levitating",
    "Artist": "Dua Lipa",
    "Date Streamed": "2024-09-02",
    "Stream Count": 3_500_000,
    "User ID": 1082,
    "Revenue Source": "ads",
    "Revenue Generated": 2.7,
  },
  {
    "Song Name": "Bohemian Rhapsody",
    "Artist": "Queen",
    "Date Streamed": "2024-09-02",
    "Stream Count": 5_200_000,
    "User ID": 1021,
    "Revenue Source": "subscription",
    "Revenue Generated": 4.5,
  },
  {
    "Song Name": "Bad Guy",
    "Artist": "Billie Eilish",
    "Date Streamed": "2024-09-02",
    "Stream Count": 2_400_000,
    "User ID": 1076,
    "Revenue Source": "ads",
    "Revenue Generated": 1.9,
  },
  {
    "Song Name": "Believer",
    "Artist": "Imagine Dragons",
    "Date Streamed": "2024-09-02",
    "Stream Count": 3_900_000,
    "User ID": 1039,
    "Revenue Source": "subscription",
    "Revenue Generated": 3.2,
  },
  {
    "Song Name": "Senorita",
    "Artist": "Shawn Mendes & Camila Cabello",
    "Date Streamed": "2024-09-02",
    "Stream Count": 3_100_000,
    "User ID": 1015,
    "Revenue Source": "ads",
    "Revenue Generated": 2.4,
  },
  {
    "Song Name": "Rolling in the Deep",
    "Artist": "Adele",
    "Date Streamed": "2024-09-02",
    "Stream Count": 2_800_000,
    "User ID": 1054,
    "Revenue Source": "subscription",
    "Revenue Generated": 2.6,
  },
  {
    "Song Name": "Sunflower",
    "Artist": "Post Malone & Swae Lee",
    "Date Streamed": "2024-09-03",
    "Stream Count": 3_750_000,
    "User ID": 1009,
    "Revenue Source": "ads",
    "Revenue Generated": 2.8,
  },
  {
    "Song Name": "Havana",
    "Artist": "Camila Cabello",
    "Date Streamed": "2024-09-03",
    "Stream Count": 4_500_000,
    "User ID": 1090,
    "Revenue Source": "subscription",
    "Revenue Generated": 3.9,
  },
  {
    "Song Name": "Can't Stop the Feeling!",
    "Artist": "Justin Timberlake",
    "Date Streamed": "2024-09-03",
    "Stream Count": 3_600_000,
    "User ID": 1089,
    "Revenue Source": "ads",
    "Revenue Generated": 2.5,
  },
  {
    "Song Name": "Counting Stars",
    "Artist": "OneRepublic",
    "Date Streamed": "2024-09-03",
    "Stream Count": 2_650_000,
    "User ID": 1035,
    "Revenue Source": "subscription",
    "Revenue Generated": 2.2,
  },
  {
    "Song Name": "Stay",
    "Artist": "The Kid LAROI & Justin Bieber",
    "Date Streamed": "2024-09-04",
    "Stream Count": 4_000_000,
    "User ID": 1024,
    "Revenue Source": "ads",
    "Revenue Generated": 3.0,
  },
  {
    "Song Name": "Watermelon Sugar",
    "Artist": "Harry Styles",
    "Date Streamed": "2024-09-04",
    "Stream Count": 2_800_000,
    "User ID": 1063,
    "Revenue Source": "subscription",
    "Revenue Generated": 2.4,
  },
  {
    "Song Name": "Shake It Off",
    "Artist": "Taylor Swift",
    "Date Streamed": "2024-09-04",
    "Stream Count": 3_200_000,
    "User ID": 1058,
    "Revenue Source": "ads",
    "Revenue Generated": 2.5,
  },
  {
    "Song Name": "Closer",
    "Artist": "The Chainsmokers",
    "Date Streamed": "2024-09-04",
    "Stream Count": 3_700_000,
    "User ID": 1071,
    "Revenue Source": "subscription",
    "Revenue Generated": 3.3,
  },
  {
    "Song Name": "Rockstar",
    "Artist": "Post Malone",
    "Date Streamed": "2024-09-05",
    "Stream Count": 4_200_000,
    "User ID": 1003,
    "Revenue Source": "ads",
    "Revenue Generated": 3.6,
  },
  {
    "Song Name": "Perfect",
    "Artist": "Ed Sheeran",
    "Date Streamed": "2024-09-05",
    "Stream Count": 5_000_000,
    "User ID": 1095,
    "Revenue Source": "subscription",
    "Revenue Generated": 4.8,
  },
  {
    "Song Name": "7 Rings",
    "Artist": "Ariana Grande",
    "Date Streamed": "2024-09-05",
    "Stream Count": 3_900_000,
    "User ID": 1087,
    "Revenue Source": "ads",
    "Revenue Generated": 3.0,
  },
  {
    "Song Name": "Memories",
    "Artist": "Maroon 5",
    "Date Streamed": "2024-09-06",
    "Stream Count": 2_400_000,
    "User ID": 1037,
    "Revenue Source": "subscription",
    "Revenue Generated": 2.1,
  },
  {
    "Song Name": "Love Yourself",
    "Artist": "Justin Bieber",
    "Date Streamed": "2024-09-06",
    "Stream Count": 3_200_000,
    "User ID": 1026,
    "Revenue Source": "ads",
    "Revenue Generated": 2.6,
  },
  {
    "Song Name": "Waka Waka",
    "Artist": "Shakira",
    "Date Streamed": "2024-09-06",
    "Stream Count": 3_800_000,
    "User ID": 1061,
    "Revenue Source": "subscription",
    "Revenue Generated": 3.4,
  },
  {
    "Song Name": "Thinking Out Loud",
    "Artist": "Ed Sheeran",
    "Date Streamed": "2024-09-07",
    "Stream Count": 2_900_000,
    "User ID": 1059,
    "Revenue Source": "ads",
    "Revenue Generated": 2.3,
  },
  {
    "Song Name": "Faded",
    "Artist": "Alan Walker",
    "Date Streamed": "2024-09-07",
    "Stream Count": 3_400_000,
    "User ID": 1073,
    "Revenue Source": "subscription",
    "Revenue Generated": 2.9,
  },
  {
    "Song Name": "We Don't Talk Anymore",
    "Artist": "Charlie Puth",
    "Date Streamed": "2024-09-07",
    "Stream Count": 2_500_000,
    "User ID": 1045,
    "Revenue Source": "ads",
    "Revenue Generated": 2.0,
  },
  {
    "Song Name": "Blinding Lights",
    "Artist": "The Weeknd",
    "Date Streamed": "2024-09-01",
    "Stream Count": 3_250_000,
    "User ID": 1042,
    "Revenue Source": "ads",
    "Revenue Generated": 2.5,
  },
  {
    "Song Name": "Shape of You",
    "Artist": "Ed Sheeran",
    "Date Streamed": "2024-09-01",
    "Stream Count": 4_100_000,
    "User ID": 1093,
    "Revenue Source": "subscription",
    "Revenue Generated": 3.8,
  },
  {
    "Song Name": "Uptown Funk",
    "Artist": "Mark Ronson ft. Bruno Mars",
    "Date Streamed": "2024-09-01",
    "Stream Count": 2_700_000,
    "User ID": 1068,
    "Revenue Source": "ads",
    "Revenue Generated": 2.1,
  },
  {
    "Song Name": "Someone Like You",
    "Artist": "Adele",
    "Date Streamed": "2024-09-01",
    "Stream Count": 1_900_000,
    "User ID": 1005,
    "Revenue Source": "subscription",
    "Revenue Generated": 1.6,
  },
  {
    "Song Name": "Levitating",
    "Artist": "Dua Lipa",
    "Date Streamed": "2024-09-02",
    "Stream Count": 3_500_000,
    "User ID": 1082,
    "Revenue Source": "ads",
    "Revenue Generated": 2.7,
  },
  {
    "Song Name": "Bohemian Rhapsody",
    "Artist": "Queen",
    "Date Streamed": "2024-09-02",
    "Stream Count": 5_200_000,
    "User ID": 1021,
    "Revenue Source": "subscription",
    "Revenue Generated": 4.5,
  },
  {
    "Song Name": "Bad Guy",
    "Artist": "Billie Eilish",
    "Date Streamed": "2024-09-02",
    "Stream Count": 2_400_000,
    "User ID": 1076,
    "Revenue Source": "ads",
    "Revenue Generated": 1.9,
  },
  {
    "Song Name": "Believer",
    "Artist": "Imagine Dragons",
    "Date Streamed": "2024-09-02",
    "Stream Count": 3_900_000,
    "User ID": 1039,
    "Revenue Source": "subscription",
    "Revenue Generated": 3.2,
  },
  {
    "Song Name": "Senorita",
    "Artist": "Shawn Mendes & Camila Cabello",
    "Date Streamed": "2024-09-02",
    "Stream Count": 3_100_000,
    "User ID": 1015,
    "Revenue Source": "ads",
    "Revenue Generated": 2.4,
  },
  {
    "Song Name": "Rolling in the Deep",
    "Artist": "Adele",
    "Date Streamed": "2024-09-02",
    "Stream Count": 2_800_000,
    "User ID": 1054,
    "Revenue Source": "subscription",
    "Revenue Generated": 2.6,
  },
  {
    "Song Name": "Sunflower",
    "Artist": "Post Malone & Swae Lee",
    "Date Streamed": "2024-09-03",
    "Stream Count": 3_750_000,
    "User ID": 1009,
    "Revenue Source": "ads",
    "Revenue Generated": 2.8,
  },
  {
    "Song Name": "Havana",
    "Artist": "Camila Cabello",
    "Date Streamed": "2024-09-03",
    "Stream Count": 4_500_000,
    "User ID": 1090,
    "Revenue Source": "subscription",
    "Revenue Generated": 3.9,
  },
  {
    "Song Name": "Can't Stop the Feeling!",
    "Artist": "Justin Timberlake",
    "Date Streamed": "2024-09-03",
    "Stream Count": 3_600_000,
    "User ID": 1089,
    "Revenue Source": "ads",
    "Revenue Generated": 2.5,
  },
  {
    "Song Name": "Counting Stars",
    "Artist": "OneRepublic",
    "Date Streamed": "2024-09-03",
    "Stream Count": 2_650_000,
    "User ID": 1035,
    "Revenue Source": "subscription",
    "Revenue Generated": 2.2,
  },
  {
    "Song Name": "Stay",
    "Artist": "The Kid LAROI & Justin Bieber",
    "Date Streamed": "2024-09-04",
    "Stream Count": 4_000_000,
    "User ID": 1024,
    "Revenue Source": "ads",
    "Revenue Generated": 3.0,
  },
  {
    "Song Name": "Watermelon Sugar",
    "Artist": "Harry Styles",
    "Date Streamed": "2024-09-04",
    "Stream Count": 2_800_000,
    "User ID": 1063,
    "Revenue Source": "subscription",
    "Revenue Generated": 2.4,
  },
  {
    "Song Name": "Shake It Off",
    "Artist": "Taylor Swift",
    "Date Streamed": "2024-09-04",
    "Stream Count": 3_200_000,
    "User ID": 1058,
    "Revenue Source": "ads",
    "Revenue Generated": 2.5,
  },
  {
    "Song Name": "Closer",
    "Artist": "The Chainsmokers",
    "Date Streamed": "2024-09-04",
    "Stream Count": 3_700_000,
    "User ID": 1071,
    "Revenue Source": "subscription",
    "Revenue Generated": 3.3,
  },
  {
    "Song Name": "Rockstar",
    "Artist": "Post Malone",
    "Date Streamed": "2024-09-05",
    "Stream Count": 4_200_000,
    "User ID": 1003,
    "Revenue Source": "ads",
    "Revenue Generated": 3.6,
  },
  {
    "Song Name": "Perfect",
    "Artist": "Ed Sheeran",
    "Date Streamed": "2024-09-05",
    "Stream Count": 5_000_000,
    "User ID": 1095,
    "Revenue Source": "subscription",
    "Revenue Generated": 4.8,
  },
  {
    "Song Name": "7 Rings",
    "Artist": "Ariana Grande",
    "Date Streamed": "2024-09-05",
    "Stream Count": 3_900_000,
    "User ID": 1087,
    "Revenue Source": "ads",
    "Revenue Generated": 3.0,
  },
  {
    "Song Name": "Memories",
    "Artist": "Maroon 5",
    "Date Streamed": "2024-09-06",
    "Stream Count": 2_400_000,
    "User ID": 1037,
    "Revenue Source": "subscription",
    "Revenue Generated": 2.1,
  },
  {
    "Song Name": "Love Yourself",
    "Artist": "Justin Bieber",
    "Date Streamed": "2024-09-06",
    "Stream Count": 3_200_000,
    "User ID": 1026,
    "Revenue Source": "ads",
    "Revenue Generated": 2.6,
  },
  {
    "Song Name": "Waka Waka",
    "Artist": "Shakira",
    "Date Streamed": "2024-09-06",
    "Stream Count": 3_800_000,
    "User ID": 1061,
    "Revenue Source": "subscription",
    "Revenue Generated": 3.4,
  },
  {
    "Song Name": "Thinking Out Loud",
    "Artist": "Ed Sheeran",
    "Date Streamed": "2024-09-07",
    "Stream Count": 2_900_000,
    "User ID": 1059,
    "Revenue Source": "ads",
    "Revenue Generated": 2.3,
  },
  {
    "Song Name": "Faded",
    "Artist": "Alan Walker",
    "Date Streamed": "2024-09-07",
    "Stream Count": 3_400_000,
    "User ID": 1073,
    "Revenue Source": "subscription",
    "Revenue Generated": 2.9,
  },
  {
    "Song Name": "We Don't Talk Anymore",
    "Artist": "Charlie Puth",
    "Date Streamed": "2024-09-07",
    "Stream Count": 2_500_000,
    "User ID": 1045,
    "Revenue Source": "ads",
    "Revenue Generated": 2.0,
  },
  {
    "Song Name": "Blinding Lights",
    "Artist": "The Weeknd",
    "Date Streamed": "2024-09-01",
    "Stream Count": 3_250_000,
    "User ID": 1042,
    "Revenue Source": "ads",
    "Revenue Generated": 2.5,
  },
  {
    "Song Name": "Shape of You",
    "Artist": "Ed Sheeran",
    "Date Streamed": "2024-09-01",
    "Stream Count": 4_100_000,
    "User ID": 1093,
    "Revenue Source": "subscription",
    "Revenue Generated": 3.8,
  },
  {
    "Song Name": "Uptown Funk",
    "Artist": "Mark Ronson ft. Bruno Mars",
    "Date Streamed": "2024-09-01",
    "Stream Count": 2_700_000,
    "User ID": 1068,
    "Revenue Source": "ads",
    "Revenue Generated": 2.1,
  },
  {
    "Song Name": "Someone Like You",
    "Artist": "Adele",
    "Date Streamed": "2024-09-01",
    "Stream Count": 1_900_000,
    "User ID": 1005,
    "Revenue Source": "subscription",
    "Revenue Generated": 1.6,
  },
  {
    "Song Name": "Levitating",
    "Artist": "Dua Lipa",
    "Date Streamed": "2024-09-02",
    "Stream Count": 3_500_000,
    "User ID": 1082,
    "Revenue Source": "ads",
    "Revenue Generated": 2.7,
  },
  {
    "Song Name": "Bohemian Rhapsody",
    "Artist": "Queen",
    "Date Streamed": "2024-09-02",
    "Stream Count": 5_200_000,
    "User ID": 1021,
    "Revenue Source": "subscription",
    "Revenue Generated": 4.5,
  },
  {
    "Song Name": "Bad Guy",
    "Artist": "Billie Eilish",
    "Date Streamed": "2024-09-02",
    "Stream Count": 2_400_000,
    "User ID": 1076,
    "Revenue Source": "ads",
    "Revenue Generated": 1.9,
  },
  {
    "Song Name": "Believer",
    "Artist": "Imagine Dragons",
    "Date Streamed": "2024-09-02",
    "Stream Count": 3_900_000,
    "User ID": 1039,
    "Revenue Source": "subscription",
    "Revenue Generated": 3.2,
  },
  {
    "Song Name": "Senorita",
    "Artist": "Shawn Mendes & Camila Cabello",
    "Date Streamed": "2024-09-02",
    "Stream Count": 3_100_000,
    "User ID": 1015,
    "Revenue Source": "ads",
    "Revenue Generated": 2.4,
  },
  {
    "Song Name": "Rolling in the Deep",
    "Artist": "Adele",
    "Date Streamed": "2024-09-02",
    "Stream Count": 2_800_000,
    "User ID": 1054,
    "Revenue Source": "subscription",
    "Revenue Generated": 2.6,
  },
  {
    "Song Name": "Sunflower",
    "Artist": "Post Malone & Swae Lee",
    "Date Streamed": "2024-09-03",
    "Stream Count": 3_750_000,
    "User ID": 1009,
    "Revenue Source": "ads",
    "Revenue Generated": 2.8,
  },
  {
    "Song Name": "Havana",
    "Artist": "Camila Cabello",
    "Date Streamed": "2024-09-03",
    "Stream Count": 4_500_000,
    "User ID": 1090,
    "Revenue Source": "subscription",
    "Revenue Generated": 3.9,
  },
  {
    "Song Name": "Can't Stop the Feeling!",
    "Artist": "Justin Timberlake",
    "Date Streamed": "2024-09-03",
    "Stream Count": 3_600_000,
    "User ID": 1089,
    "Revenue Source": "ads",
    "Revenue Generated": 2.5,
  },
  {
    "Song Name": "Counting Stars",
    "Artist": "OneRepublic",
    "Date Streamed": "2024-09-03",
    "Stream Count": 2_650_000,
    "User ID": 1035,
    "Revenue Source": "subscription",
    "Revenue Generated": 2.2,
  },
  {
    "Song Name": "Stay",
    "Artist": "The Kid LAROI & Justin Bieber",
    "Date Streamed": "2024-09-04",
    "Stream Count": 4_000_000,
    "User ID": 1024,
    "Revenue Source": "ads",
    "Revenue Generated": 3.0,
  },
  {
    "Song Name": "Watermelon Sugar",
    "Artist": "Harry Styles",
    "Date Streamed": "2024-09-04",
    "Stream Count": 2_800_000,
    "User ID": 1063,
    "Revenue Source": "subscription",
    "Revenue Generated": 2.4,
  },
  {
    "Song Name": "Shake It Off",
    "Artist": "Taylor Swift",
    "Date Streamed": "2024-09-04",
    "Stream Count": 3_200_000,
    "User ID": 1058,
    "Revenue Source": "ads",
    "Revenue Generated": 2.5,
  },
  {
    "Song Name": "Closer",
    "Artist": "The Chainsmokers",
    "Date Streamed": "2024-09-04",
    "Stream Count": 3_700_000,
    "User ID": 1071,
    "Revenue Source": "subscription",
    "Revenue Generated": 3.3,
  },
  {
    "Song Name": "Rockstar",
    "Artist": "Post Malone",
    "Date Streamed": "2024-09-05",
    "Stream Count": 4_200_000,
    "User ID": 1003,
    "Revenue Source": "ads",
    "Revenue Generated": 3.6,
  },
  {
    "Song Name": "Perfect",
    "Artist": "Ed Sheeran",
    "Date Streamed": "2024-09-05",
    "Stream Count": 5_000_000,
    "User ID": 1095,
    "Revenue Source": "subscription",
    "Revenue Generated": 4.8,
  },
  {
    "Song Name": "7 Rings",
    "Artist": "Ariana Grande",
    "Date Streamed": "2024-09-05",
    "Stream Count": 3_900_000,
    "User ID": 1087,
    "Revenue Source": "ads",
    "Revenue Generated": 3.0,
  },
  {
    "Song Name": "Memories",
    "Artist": "Maroon 5",
    "Date Streamed": "2024-09-06",
    "Stream Count": 2_400_000,
    "User ID": 1037,
    "Revenue Source": "subscription",
    "Revenue Generated": 2.1,
  },
  {
    "Song Name": "Love Yourself",
    "Artist": "Justin Bieber",
    "Date Streamed": "2024-09-06",
    "Stream Count": 3_200_000,
    "User ID": 1026,
    "Revenue Source": "ads",
    "Revenue Generated": 2.6,
  },
  {
    "Song Name": "Waka Waka",
    "Artist": "Shakira",
    "Date Streamed": "2024-09-06",
    "Stream Count": 3_800_000,
    "User ID": 1061,
    "Revenue Source": "subscription",
    "Revenue Generated": 3.4,
  },
  {
    "Song Name": "Thinking Out Loud",
    "Artist": "Ed Sheeran",
    "Date Streamed": "2024-09-07",
    "Stream Count": 2_900_000,
    "User ID": 1059,
    "Revenue Source": "ads",
    "Revenue Generated": 2.3,
  },
  {
    "Song Name": "Faded",
    "Artist": "Alan Walker",
    "Date Streamed": "2024-09-07",
    "Stream Count": 3_400_000,
    "User ID": 1073,
    "Revenue Source": "subscription",
    "Revenue Generated": 2.9,
  },
  {
    "Song Name": "We Don't Talk Anymore",
    "Artist": "Charlie Puth",
    "Date Streamed": "2024-09-07",
    "Stream Count": 2_500_000,
    "User ID": 1045,
    "Revenue Source": "ads",
    "Revenue Generated": 2.0,
  },
  {
    "Song Name": "Blinding Lights",
    "Artist": "The Weeknd",
    "Date Streamed": "2024-09-01",
    "Stream Count": 3_250_000,
    "User ID": 1042,
    "Revenue Source": "ads",
    "Revenue Generated": 2.5,
  },
  {
    "Song Name": "Shape of You",
    "Artist": "Ed Sheeran",
    "Date Streamed": "2024-09-01",
    "Stream Count": 4_100_000,
    "User ID": 1093,
    "Revenue Source": "subscription",
    "Revenue Generated": 3.8,
  },
  {
    "Song Name": "Uptown Funk",
    "Artist": "Mark Ronson ft. Bruno Mars",
    "Date Streamed": "2024-09-01",
    "Stream Count": 2_700_000,
    "User ID": 1068,
    "Revenue Source": "ads",
    "Revenue Generated": 2.1,
  },
  {
    "Song Name": "Someone Like You",
    "Artist": "Adele",
    "Date Streamed": "2024-09-01",
    "Stream Count": 1_900_000,
    "User ID": 1005,
    "Revenue Source": "subscription",
    "Revenue Generated": 1.6,
  },
  {
    "Song Name": "Levitating",
    "Artist": "Dua Lipa",
    "Date Streamed": "2024-09-02",
    "Stream Count": 3_500_000,
    "User ID": 1082,
    "Revenue Source": "ads",
    "Revenue Generated": 2.7,
  },
  {
    "Song Name": "Bohemian Rhapsody",
    "Artist": "Queen",
    "Date Streamed": "2024-09-02",
    "Stream Count": 5_200_000,
    "User ID": 1021,
    "Revenue Source": "subscription",
    "Revenue Generated": 4.5,
  },
  {
    "Song Name": "Bad Guy",
    "Artist": "Billie Eilish",
    "Date Streamed": "2024-09-02",
    "Stream Count": 2_400_000,
    "User ID": 1076,
    "Revenue Source": "ads",
    "Revenue Generated": 1.9,
  },
  {
    "Song Name": "Believer",
    "Artist": "Imagine Dragons",
    "Date Streamed": "2024-09-02",
    "Stream Count": 3_900_000,
    "User ID": 1039,
    "Revenue Source": "subscription",
    "Revenue Generated": 3.2,
  },
  {
    "Song Name": "Senorita",
    "Artist": "Shawn Mendes & Camila Cabello",
    "Date Streamed": "2024-09-02",
    "Stream Count": 3_100_000,
    "User ID": 1015,
    "Revenue Source": "ads",
    "Revenue Generated": 2.4,
  },
  {
    "Song Name": "Rolling in the Deep",
    "Artist": "Adele",
    "Date Streamed": "2024-09-02",
    "Stream Count": 2_800_000,
    "User ID": 1054,
    "Revenue Source": "subscription",
    "Revenue Generated": 2.6,
  },
  {
    "Song Name": "Sunflower",
    "Artist": "Post Malone & Swae Lee",
    "Date Streamed": "2024-09-03",
    "Stream Count": 3_750_000,
    "User ID": 1009,
    "Revenue Source": "ads",
    "Revenue Generated": 2.8,
  },
  {
    "Song Name": "Havana",
    "Artist": "Camila Cabello",
    "Date Streamed": "2024-09-03",
    "Stream Count": 4_500_000,
    "User ID": 1090,
    "Revenue Source": "subscription",
    "Revenue Generated": 3.9,
  },
  {
    "Song Name": "Can't Stop the Feeling!",
    "Artist": "Justin Timberlake",
    "Date Streamed": "2024-09-03",
    "Stream Count": 3_600_000,
    "User ID": 1089,
    "Revenue Source": "ads",
    "Revenue Generated": 2.5,
  },
  {
    "Song Name": "Counting Stars",
    "Artist": "OneRepublic",
    "Date Streamed": "2024-09-03",
    "Stream Count": 2_650_000,
    "User ID": 1035,
    "Revenue Source": "subscription",
    "Revenue Generated": 2.2,
  },
  {
    "Song Name": "Stay",
    "Artist": "The Kid LAROI & Justin Bieber",
    "Date Streamed": "2024-09-04",
    "Stream Count": 4_000_000,
    "User ID": 1024,
    "Revenue Source": "ads",
    "Revenue Generated": 3.0,
  },
  {
    "Song Name": "Watermelon Sugar",
    "Artist": "Harry Styles",
    "Date Streamed": "2024-09-04",
    "Stream Count": 2_800_000,
    "User ID": 1063,
    "Revenue Source": "subscription",
    "Revenue Generated": 2.4,
  },
  {
    "Song Name": "Shake It Off",
    "Artist": "Taylor Swift",
    "Date Streamed": "2024-09-04",
    "Stream Count": 3_200_000,
    "User ID": 1058,
    "Revenue Source": "ads",
    "Revenue Generated": 2.5,
  },
  {
    "Song Name": "Closer",
    "Artist": "The Chainsmokers",
    "Date Streamed": "2024-09-04",
    "Stream Count": 3_700_000,
    "User ID": 1071,
    "Revenue Source": "subscription",
    "Revenue Generated": 3.3,
  },
  {
    "Song Name": "Rockstar",
    "Artist": "Post Malone",
    "Date Streamed": "2024-09-05",
    "Stream Count": 4_200_000,
    "User ID": 1003,
    "Revenue Source": "ads",
    "Revenue Generated": 3.6,
  },
  {
    "Song Name": "Perfect",
    "Artist": "Ed Sheeran",
    "Date Streamed": "2024-09-05",
    "Stream Count": 5_000_000,
    "User ID": 1095,
    "Revenue Source": "subscription",
    "Revenue Generated": 4.8,
  },
  {
    "Song Name": "7 Rings",
    "Artist": "Ariana Grande",
    "Date Streamed": "2024-09-05",
    "Stream Count": 3_900_000,
    "User ID": 1087,
    "Revenue Source": "ads",
    "Revenue Generated": 3.0,
  },
  {
    "Song Name": "Memories",
    "Artist": "Maroon 5",
    "Date Streamed": "2024-09-06",
    "Stream Count": 2_400_000,
    "User ID": 1037,
    "Revenue Source": "subscription",
    "Revenue Generated": 2.1,
  },
  {
    "Song Name": "Love Yourself",
    "Artist": "Justin Bieber",
    "Date Streamed": "2024-09-06",
    "Stream Count": 3_200_000,
    "User ID": 1026,
    "Revenue Source": "ads",
    "Revenue Generated": 2.6,
  },
  {
    "Song Name": "Waka Waka",
    "Artist": "Shakira",
    "Date Streamed": "2024-09-06",
    "Stream Count": 3_800_000,
    "User ID": 1061,
    "Revenue Source": "subscription",
    "Revenue Generated": 3.4,
  },
  {
    "Song Name": "Thinking Out Loud",
    "Artist": "Ed Sheeran",
    "Date Streamed": "2024-09-07",
    "Stream Count": 2_900_000,
    "User ID": 1059,
    "Revenue Source": "ads",
    "Revenue Generated": 2.3,
  },
  {
    "Song Name": "Faded",
    "Artist": "Alan Walker",
    "Date Streamed": "2024-09-07",
    "Stream Count": 3_400_000,
    "User ID": 1073,
    "Revenue Source": "subscription",
    "Revenue Generated": 2.9,
  },
  {
    "Song Name": "We Don't Talk Anymore",
    "Artist": "Charlie Puth",
    "Date Streamed": "2024-09-07",
    "Stream Count": 2_500_000,
    "User ID": 1045,
    "Revenue Source": "ads",
    "Revenue Generated": 2.0,
  },
  {
    "Song Name": "Blinding Lights",
    "Artist": "The Weeknd",
    "Date Streamed": "2024-09-01",
    "Stream Count": 3_250_000,
    "User ID": 1042,
    "Revenue Source": "ads",
    "Revenue Generated": 2.5,
  },
  {
    "Song Name": "Shape of You",
    "Artist": "Ed Sheeran",
    "Date Streamed": "2024-09-01",
    "Stream Count": 4_100_000,
    "User ID": 1093,
    "Revenue Source": "subscription",
    "Revenue Generated": 3.8,
  },
  {
    "Song Name": "Uptown Funk",
    "Artist": "Mark Ronson ft. Bruno Mars",
    "Date Streamed": "2024-09-01",
    "Stream Count": 2_700_000,
    "User ID": 1068,
    "Revenue Source": "ads",
    "Revenue Generated": 2.1,
  },
  {
    "Song Name": "Someone Like You",
    "Artist": "Adele",
    "Date Streamed": "2024-09-01",
    "Stream Count": 1_900_000,
    "User ID": 1005,
    "Revenue Source": "subscription",
    "Revenue Generated": 1.6,
  },
  {
    "Song Name": "Levitating",
    "Artist": "Dua Lipa",
    "Date Streamed": "2024-09-02",
    "Stream Count": 3_500_000,
    "User ID": 1082,
    "Revenue Source": "ads",
    "Revenue Generated": 2.7,
  },
  {
    "Song Name": "Bohemian Rhapsody",
    "Artist": "Queen",
    "Date Streamed": "2024-09-02",
    "Stream Count": 5_200_000,
    "User ID": 1021,
    "Revenue Source": "subscription",
    "Revenue Generated": 4.5,
  },
  {
    "Song Name": "Bad Guy",
    "Artist": "Billie Eilish",
    "Date Streamed": "2024-09-02",
    "Stream Count": 2_400_000,
    "User ID": 1076,
    "Revenue Source": "ads",
    "Revenue Generated": 1.9,
  },
  {
    "Song Name": "Believer",
    "Artist": "Imagine Dragons",
    "Date Streamed": "2024-09-02",
    "Stream Count": 3_900_000,
    "User ID": 1039,
    "Revenue Source": "subscription",
    "Revenue Generated": 3.2,
  },
  {
    "Song Name": "Senorita",
    "Artist": "Shawn Mendes & Camila Cabello",
    "Date Streamed": "2024-09-02",
    "Stream Count": 3_100_000,
    "User ID": 1015,
    "Revenue Source": "ads",
    "Revenue Generated": 2.4,
  },
  {
    "Song Name": "Rolling in the Deep",
    "Artist": "Adele",
    "Date Streamed": "2024-09-02",
    "Stream Count": 2_800_000,
    "User ID": 1054,
    "Revenue Source": "subscription",
    "Revenue Generated": 2.6,
  },
  {
    "Song Name": "Sunflower",
    "Artist": "Post Malone & Swae Lee",
    "Date Streamed": "2024-09-03",
    "Stream Count": 3_750_000,
    "User ID": 1009,
    "Revenue Source": "ads",
    "Revenue Generated": 2.8,
  },
  {
    "Song Name": "Havana",
    "Artist": "Camila Cabello",
    "Date Streamed": "2024-09-03",
    "Stream Count": 4_500_000,
    "User ID": 1090,
    "Revenue Source": "subscription",
    "Revenue Generated": 3.9,
  },
  {
    "Song Name": "Can't Stop the Feeling!",
    "Artist": "Justin Timberlake",
    "Date Streamed": "2024-09-03",
    "Stream Count": 3_600_000,
    "User ID": 1089,
    "Revenue Source": "ads",
    "Revenue Generated": 2.5,
  },
  {
    "Song Name": "Counting Stars",
    "Artist": "OneRepublic",
    "Date Streamed": "2024-09-03",
    "Stream Count": 2_650_000,
    "User ID": 1035,
    "Revenue Source": "subscription",
    "Revenue Generated": 2.2,
  },
  {
    "Song Name": "Stay",
    "Artist": "The Kid LAROI & Justin Bieber",
    "Date Streamed": "2024-09-04",
    "Stream Count": 4_000_000,
    "User ID": 1024,
    "Revenue Source": "ads",
    "Revenue Generated": 3.0,
  },
  {
    "Song Name": "Watermelon Sugar",
    "Artist": "Harry Styles",
    "Date Streamed": "2024-09-04",
    "Stream Count": 2_800_000,
    "User ID": 1063,
    "Revenue Source": "subscription",
    "Revenue Generated": 2.4,
  },
  {
    "Song Name": "Shake It Off",
    "Artist": "Taylor Swift",
    "Date Streamed": "2024-09-04",
    "Stream Count": 3_200_000,
    "User ID": 1058,
    "Revenue Source": "ads",
    "Revenue Generated": 2.5,
  },
  {
    "Song Name": "Closer",
    "Artist": "The Chainsmokers",
    "Date Streamed": "2024-09-04",
    "Stream Count": 3_700_000,
    "User ID": 1071,
    "Revenue Source": "subscription",
    "Revenue Generated": 3.3,
  },
  {
    "Song Name": "Rockstar",
    "Artist": "Post Malone",
    "Date Streamed": "2024-09-05",
    "Stream Count": 4_200_000,
    "User ID": 1003,
    "Revenue Source": "ads",
    "Revenue Generated": 3.6,
  },
  {
    "Song Name": "Perfect",
    "Artist": "Ed Sheeran",
    "Date Streamed": "2024-09-05",
    "Stream Count": 5_000_000,
    "User ID": 1095,
    "Revenue Source": "subscription",
    "Revenue Generated": 4.8,
  },
  {
    "Song Name": "7 Rings",
    "Artist": "Ariana Grande",
    "Date Streamed": "2024-09-05",
    "Stream Count": 3_900_000,
    "User ID": 1087,
    "Revenue Source": "ads",
    "Revenue Generated": 3.0,
  },
  {
    "Song Name": "Memories",
    "Artist": "Maroon 5",
    "Date Streamed": "2024-09-06",
    "Stream Count": 2_400_000,
    "User ID": 1037,
    "Revenue Source": "subscription",
    "Revenue Generated": 2.1,
  },
  {
    "Song Name": "Love Yourself",
    "Artist": "Justin Bieber",
    "Date Streamed": "2024-09-06",
    "Stream Count": 3_200_000,
    "User ID": 1026,
    "Revenue Source": "ads",
    "Revenue Generated": 2.6,
  },
  {
    "Song Name": "Waka Waka",
    "Artist": "Shakira",
    "Date Streamed": "2024-09-06",
    "Stream Count": 3_800_000,
    "User ID": 1061,
    "Revenue Source": "subscription",
    "Revenue Generated": 3.4,
  },
  {
    "Song Name": "Thinking Out Loud",
    "Artist": "Ed Sheeran",
    "Date Streamed": "2024-09-07",
    "Stream Count": 2_900_000,
    "User ID": 1059,
    "Revenue Source": "ads",
    "Revenue Generated": 2.3,
  },
  {
    "Song Name": "Faded",
    "Artist": "Alan Walker",
    "Date Streamed": "2024-09-07",
    "Stream Count": 3_400_000,
    "User ID": 1073,
    "Revenue Source": "subscription",
    "Revenue Generated": 2.9,
  },
  {
    "Song Name": "We Don't Talk Anymore",
    "Artist": "Charlie Puth",
    "Date Streamed": "2024-09-07",
    "Stream Count": 2_500_000,
    "User ID": 1045,
    "Revenue Source": "ads",
    "Revenue Generated": 2.0,
  },
  {
    "Song Name": "Blinding Lights",
    "Artist": "The Weeknd",
    "Date Streamed": "2024-09-01",
    "Stream Count": 3_250_000,
    "User ID": 1042,
    "Revenue Source": "ads",
    "Revenue Generated": 2.5,
  },
  {
    "Song Name": "Shape of You",
    "Artist": "Ed Sheeran",
    "Date Streamed": "2024-09-01",
    "Stream Count": 4_100_000,
    "User ID": 1093,
    "Revenue Source": "subscription",
    "Revenue Generated": 3.8,
  },
  {
    "Song Name": "Uptown Funk",
    "Artist": "Mark Ronson ft. Bruno Mars",
    "Date Streamed": "2024-09-01",
    "Stream Count": 2_700_000,
    "User ID": 1068,
    "Revenue Source": "ads",
    "Revenue Generated": 2.1,
  },
  {
    "Song Name": "Someone Like You",
    "Artist": "Adele",
    "Date Streamed": "2024-09-01",
    "Stream Count": 1_900_000,
    "User ID": 1005,
    "Revenue Source": "subscription",
    "Revenue Generated": 1.6,
  },
  {
    "Song Name": "Levitating",
    "Artist": "Dua Lipa",
    "Date Streamed": "2024-09-02",
    "Stream Count": 3_500_000,
    "User ID": 1082,
    "Revenue Source": "ads",
    "Revenue Generated": 2.7,
  },
  {
    "Song Name": "Bohemian Rhapsody",
    "Artist": "Queen",
    "Date Streamed": "2024-09-02",
    "Stream Count": 5_200_000,
    "User ID": 1021,
    "Revenue Source": "subscription",
    "Revenue Generated": 4.5,
  },
  {
    "Song Name": "Bad Guy",
    "Artist": "Billie Eilish",
    "Date Streamed": "2024-09-02",
    "Stream Count": 2_400_000,
    "User ID": 1076,
    "Revenue Source": "ads",
    "Revenue Generated": 1.9,
  },
  {
    "Song Name": "Believer",
    "Artist": "Imagine Dragons",
    "Date Streamed": "2024-09-02",
    "Stream Count": 3_900_000,
    "User ID": 1039,
    "Revenue Source": "subscription",
    "Revenue Generated": 3.2,
  },
  {
    "Song Name": "Senorita",
    "Artist": "Shawn Mendes & Camila Cabello",
    "Date Streamed": "2024-09-02",
    "Stream Count": 3_100_000,
    "User ID": 1015,
    "Revenue Source": "ads",
    "Revenue Generated": 2.4,
  },
  {
    "Song Name": "Rolling in the Deep",
    "Artist": "Adele",
    "Date Streamed": "2024-09-02",
    "Stream Count": 2_800_000,
    "User ID": 1054,
    "Revenue Source": "subscription",
    "Revenue Generated": 2.6,
  },
  {
    "Song Name": "Sunflower",
    "Artist": "Post Malone & Swae Lee",
    "Date Streamed": "2024-09-03",
    "Stream Count": 3_750_000,
    "User ID": 1009,
    "Revenue Source": "ads",
    "Revenue Generated": 2.8,
  },
  {
    "Song Name": "Havana",
    "Artist": "Camila Cabello",
    "Date Streamed": "2024-09-03",
    "Stream Count": 4_500_000,
    "User ID": 1090,
    "Revenue Source": "subscription",
    "Revenue Generated": 3.9,
  },
  {
    "Song Name": "Can't Stop the Feeling!",
    "Artist": "Justin Timberlake",
    "Date Streamed": "2024-09-03",
    "Stream Count": 3_600_000,
    "User ID": 1089,
    "Revenue Source": "ads",
    "Revenue Generated": 2.5,
  },
  {
    "Song Name": "Counting Stars",
    "Artist": "OneRepublic",
    "Date Streamed": "2024-09-03",
    "Stream Count": 2_650_000,
    "User ID": 1035,
    "Revenue Source": "subscription",
    "Revenue Generated": 2.2,
  },
  {
    "Song Name": "Stay",
    "Artist": "The Kid LAROI & Justin Bieber",
    "Date Streamed": "2024-09-04",
    "Stream Count": 4_000_000,
    "User ID": 1024,
    "Revenue Source": "ads",
    "Revenue Generated": 3.0,
  },
  {
    "Song Name": "Watermelon Sugar",
    "Artist": "Harry Styles",
    "Date Streamed": "2024-09-04",
    "Stream Count": 2_800_000,
    "User ID": 1063,
    "Revenue Source": "subscription",
    "Revenue Generated": 2.4,
  },
  {
    "Song Name": "Shake It Off",
    "Artist": "Taylor Swift",
    "Date Streamed": "2024-09-04",
    "Stream Count": 3_200_000,
    "User ID": 1058,
    "Revenue Source": "ads",
    "Revenue Generated": 2.5,
  },
  {
    "Song Name": "Closer",
    "Artist": "The Chainsmokers",
    "Date Streamed": "2024-09-04",
    "Stream Count": 3_700_000,
    "User ID": 1071,
    "Revenue Source": "subscription",
    "Revenue Generated": 3.3,
  },
  {
    "Song Name": "Rockstar",
    "Artist": "Post Malone",
    "Date Streamed": "2024-09-05",
    "Stream Count": 4_200_000,
    "User ID": 1003,
    "Revenue Source": "ads",
    "Revenue Generated": 3.6,
  },
  {
    "Song Name": "Perfect",
    "Artist": "Ed Sheeran",
    "Date Streamed": "2024-09-05",
    "Stream Count": 5_000_000,
    "User ID": 1095,
    "Revenue Source": "subscription",
    "Revenue Generated": 4.8,
  },
  {
    "Song Name": "7 Rings",
    "Artist": "Ariana Grande",
    "Date Streamed": "2024-09-05",
    "Stream Count": 3_900_000,
    "User ID": 1087,
    "Revenue Source": "ads",
    "Revenue Generated": 3.0,
  },
  {
    "Song Name": "Memories",
    "Artist": "Maroon 5",
    "Date Streamed": "2024-09-06",
    "Stream Count": 2_400_000,
    "User ID": 1037,
    "Revenue Source": "subscription",
    "Revenue Generated": 2.1,
  },
  {
    "Song Name": "Love Yourself",
    "Artist": "Justin Bieber",
    "Date Streamed": "2024-09-06",
    "Stream Count": 3_200_000,
    "User ID": 1026,
    "Revenue Source": "ads",
    "Revenue Generated": 2.6,
  },
  {
    "Song Name": "Waka Waka",
    "Artist": "Shakira",
    "Date Streamed": "2024-09-06",
    "Stream Count": 3_800_000,
    "User ID": 1061,
    "Revenue Source": "subscription",
    "Revenue Generated": 3.4,
  },
  {
    "Song Name": "Thinking Out Loud",
    "Artist": "Ed Sheeran",
    "Date Streamed": "2024-09-07",
    "Stream Count": 2_900_000,
    "User ID": 1059,
    "Revenue Source": "ads",
    "Revenue Generated": 2.3,
  },
  {
    "Song Name": "Faded",
    "Artist": "Alan Walker",
    "Date Streamed": "2024-09-07",
    "Stream Count": 3_400_000,
    "User ID": 1073,
    "Revenue Source": "subscription",
    "Revenue Generated": 2.9,
  },
  {
    "Song Name": "We Don't Talk Anymore",
    "Artist": "Charlie Puth",
    "Date Streamed": "2024-09-07",
    "Stream Count": 2_500_000,
    "User ID": 1045,
    "Revenue Source": "ads",
    "Revenue Generated": 2.0,
  },
];

